server:
  port: 9999
# 微服务名称，注入到Eureka容器中
spring:
  application:
    name: quantity-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
  server:
    eviction-interval-timer-in-ms: 500 # 剔除无效连接的间隔
    enable-self-preservation: false # 关闭自我保护状态
